services:
  tetris_game:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    networks:
      - dokalab_host_network
    restart: always

networks:
  dokalab_host_network:
    external: true